10/01 03:01:38 AM: Git branch: master
10/01 03:01:38 AM: Git SHA: 62183b2d03f2fae12b41eef8779808b6d354875e
10/01 03:01:38 AM: Parsed args: 
{
  "allow_missing_task_map": 1,
  "allow_untrained_encoder_parameters": 1,
  "do_pretrain": 0,
  "exp_dir": "./experiments/pos-ontonotes-sstrandom-top/",
  "exp_name": "experiments/pos-ontonotes-sstrandom-top",
  "input_module": "bert-base-uncased",
  "local_log_path": "./experiments/pos-ontonotes-sstrandom-top/run/log.log",
  "lr_patience": 3,
  "max_seq_len": 512,
  "output_mode": "top",
  "patience": 9,
  "pretrain_tasks": "",
  "pretrained_dir": "models/sstrandom",
  "pytorch_transformers_output_mode": "top",
  "remote_log_name": "experiments/pos-ontonotes-sstrandom-top__run",
  "run_dir": "./experiments/pos-ontonotes-sstrandom-top/run",
  "run_name": "run",
  "sent_enc": "none",
  "sep_embs_for_skip": 1,
  "target_tasks": "edges-pos-ontonotes",
  "tokenizer": "bert-base-uncased",
  "write_preds": "val,test"
}
10/01 03:01:38 AM: Saved config to ./experiments/pos-ontonotes-sstrandom-top/run/params.conf
10/01 03:01:38 AM: Using random seed 1234
10/01 03:01:42 AM: Using GPU 0
10/01 03:01:42 AM: Loading tasks...
10/01 03:01:42 AM: Writing pre-preprocessed tasks to ./experiments/pos-ontonotes-sstrandom-top/
10/01 03:01:42 AM: 	Creating task edges-pos-ontonotes from scratch.
10/01 03:01:42 AM: Fatal error in main():
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    main(sys.argv[1:])
  File "/srv/home/ericwallace/jiant/jiant/__main__.py", line 502, in main
    pretrain_tasks, target_tasks, vocab, word_embs = build_tasks(args)
  File "/srv/home/ericwallace/jiant/jiant/preprocess.py", line 295, in build_tasks
    tasks, pretrain_task_names, target_task_names = get_tasks(args)
  File "/srv/home/ericwallace/jiant/jiant/preprocess.py", line 480, in get_tasks
    task = _get_task(name, args, data_path=data_path, scratch_path=scratch_path)
  File "/srv/home/ericwallace/jiant/jiant/preprocess.py", line 442, in _get_task
    task.load_data()
  File "/srv/home/ericwallace/jiant/jiant/tasks/edge_probing.py", line 150, in load_data
    self.all_labels = list(utils.load_lines(self.label_file))
  File "/srv/home/ericwallace/jiant/jiant/utils/utils.py", line 409, in load_lines
    with open(filename) as fd:
FileNotFoundError: [Errno 2] No such file or directory: './probing_data/edges/ontonotes/const/pos/labels.txt'
