09/16 07:17:15 AM: Git branch: master
09/16 07:17:15 AM: Git SHA: 36ca31498698840426ebb6bc0a6246f741bc664e
09/16 07:17:16 AM: Parsed args: 
{
  "allow_missing_task_map": 1,
  "allow_untrained_encoder_parameters": 1,
  "do_pretrain": 0,
  "exp_dir": "./experiments/rel-semeval-None-only/",
  "exp_name": "experiments/rel-semeval-None-only",
  "input_module": "bert-base-uncased",
  "local_log_path": "./experiments/rel-semeval-None-only/run/log.log",
  "lr_patience": 3,
  "max_seq_len": 512,
  "output_mode": "top",
  "patience": 9,
  "pretrain_tasks": "",
  "pretrained_dir": "models/None",
  "pytorch_transformers_output_mode": "only",
  "remote_log_name": "experiments/rel-semeval-None-only__run",
  "run_dir": "./experiments/rel-semeval-None-only/run",
  "run_name": "run",
  "sent_enc": "none",
  "sep_embs_for_skip": 1,
  "target_tasks": "edges-rel-semeval",
  "tokenizer": "bert-base-uncased",
  "write_preds": "val,test"
}
09/16 07:17:16 AM: Saved config to ./experiments/rel-semeval-None-only/run/params.conf
09/16 07:17:16 AM: Using random seed 1234
09/16 07:17:16 AM: Using GPU 0
09/16 07:17:16 AM: Loading tasks...
09/16 07:17:16 AM: Writing pre-preprocessed tasks to ./experiments/rel-semeval-None-only/
09/16 07:17:16 AM: 	Creating task edges-rel-semeval from scratch.
09/16 07:17:17 AM: Read=6851, Skip=0, Total=6851 from ./probing_data/edges/semeval/train.0.85.json.retokenized.bert-base-uncased
09/16 07:17:17 AM: Read=1149, Skip=0, Total=1149 from ./probing_data/edges/semeval/dev.json.retokenized.bert-base-uncased
09/16 07:17:17 AM: Read=2717, Skip=0, Total=2717 from ./probing_data/edges/semeval/test.json.retokenized.bert-base-uncased
09/16 07:17:17 AM: 	Task 'edges-rel-semeval': |train|=6851 |val|=1149 |test|=2717
09/16 07:17:17 AM: 	Finished loading tasks: edges-rel-semeval.
09/16 07:17:17 AM: 	Building vocab from scratch.
09/16 07:17:17 AM: 	Counting units for task edges-rel-semeval.
09/16 07:17:17 AM: 	Task 'edges-rel-semeval': adding vocab namespace 'edges-rel-semeval_labels'
09/16 07:17:18 AM: loading file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /home/ericwallace/.cache/torch/pytorch_transformers/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
09/16 07:17:18 AM: Added pytorch_transformers vocab (bert-base-uncased): 30522 tokens
09/16 07:17:18 AM: 	Saved vocab to ./experiments/rel-semeval-None-only/vocab
09/16 07:17:18 AM: Loading token dictionary from ./experiments/rel-semeval-None-only/vocab.
09/16 07:17:18 AM: 	Loaded vocab from ./experiments/rel-semeval-None-only/vocab
09/16 07:17:18 AM: 	Vocab namespace bert_uncased: size 30524
09/16 07:17:18 AM: 	Vocab namespace tokens: size 16020
09/16 07:17:18 AM: 	Vocab namespace chars: size 59
09/16 07:17:18 AM: 	Vocab namespace edges-rel-semeval_labels: size 19
09/16 07:17:18 AM: 	Finished building vocab.
09/16 07:17:18 AM: 	Task edges-rel-semeval (train): Indexing from scratch.
09/16 07:17:19 AM: 	Task edges-rel-semeval (train): Saved 6851 instances to ./experiments/rel-semeval-None-only/preproc/edges-rel-semeval__train_data
09/16 07:17:19 AM: 	Task edges-rel-semeval (val): Indexing from scratch.
09/16 07:17:19 AM: 	Task edges-rel-semeval (val): Saved 1149 instances to ./experiments/rel-semeval-None-only/preproc/edges-rel-semeval__val_data
09/16 07:17:19 AM: 	Task edges-rel-semeval (test): Indexing from scratch.
09/16 07:17:19 AM: 	Task edges-rel-semeval (test): Saved 2717 instances to ./experiments/rel-semeval-None-only/preproc/edges-rel-semeval__test_data
09/16 07:17:19 AM: 	Finished indexing tasks
09/16 07:17:19 AM: 	Creating trimmed target-only version of edges-rel-semeval train.
09/16 07:17:19 AM: 	  Training on 
09/16 07:17:19 AM: 	  Evaluating on edges-rel-semeval
09/16 07:17:19 AM: 	Finished loading tasks in 2.703s
09/16 07:17:19 AM: 	 Tasks: ['edges-rel-semeval']
09/16 07:17:19 AM: Building model...
09/16 07:17:19 AM: Using BERT model (bert-base-uncased).
09/16 07:17:19 AM: LOADING A PRETRAINED MODEL
09/16 07:17:20 AM: https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json not found in cache or force_download set to True, downloading to /tmp/tmpeg5j3zte
09/16 07:17:21 AM: copying /tmp/tmpeg5j3zte to cache at ./experiments/rel-semeval-None-only/pytorch_transformers_cache/4dad0251492946e18ac39290fcfe91b89d370fee250efe9521476438fe8ca185.bf3b9ea126d8c0001ee8a1e8b92229871d06d36d8808208cc2449280da87785c
09/16 07:17:21 AM: creating metadata file for ./experiments/rel-semeval-None-only/pytorch_transformers_cache/4dad0251492946e18ac39290fcfe91b89d370fee250efe9521476438fe8ca185.bf3b9ea126d8c0001ee8a1e8b92229871d06d36d8808208cc2449280da87785c
09/16 07:17:21 AM: removing temp file /tmp/tmpeg5j3zte
09/16 07:17:21 AM: loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json from cache at ./experiments/rel-semeval-None-only/pytorch_transformers_cache/4dad0251492946e18ac39290fcfe91b89d370fee250efe9521476438fe8ca185.bf3b9ea126d8c0001ee8a1e8b92229871d06d36d8808208cc2449280da87785c
09/16 07:17:21 AM: Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 2,
  "output_attentions": false,
  "output_hidden_states": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

09/16 07:17:22 AM: https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-pytorch_model.bin not found in cache or force_download set to True, downloading to /tmp/tmp9n6md9tq
09/16 07:23:10 AM: Couldn't reach server at 'https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-pytorch_model.bin' to download pretrained weights.
09/16 07:23:10 AM: Fatal error in main():
Traceback (most recent call last):
  File "/home/ericwallace/miniconda3/envs/jiant/lib/python3.6/site-packages/urllib3/response.py", line 397, in _error_catcher
    yield
  File "/home/ericwallace/miniconda3/envs/jiant/lib/python3.6/site-packages/urllib3/response.py", line 479, in read
    data = self._fp.read(amt)
  File "/home/ericwallace/miniconda3/envs/jiant/lib/python3.6/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/home/ericwallace/miniconda3/envs/jiant/lib/python3.6/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/home/ericwallace/miniconda3/envs/jiant/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/ericwallace/miniconda3/envs/jiant/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/home/ericwallace/miniconda3/envs/jiant/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/home/ericwallace/miniconda3/envs/jiant/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ericwallace/miniconda3/envs/jiant/lib/python3.6/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/ericwallace/miniconda3/envs/jiant/lib/python3.6/site-packages/urllib3/response.py", line 531, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/ericwallace/miniconda3/envs/jiant/lib/python3.6/site-packages/urllib3/response.py", line 496, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/home/ericwallace/miniconda3/envs/jiant/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ericwallace/miniconda3/envs/jiant/lib/python3.6/site-packages/urllib3/response.py", line 415, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 16, in <module>
    main(sys.argv[1:])
  File "/srv/home/ericwallace/jiant/jiant/__main__.py", line 510, in main
    model = build_model(args, vocab, word_embs, tasks)
  File "/srv/home/ericwallace/jiant/jiant/models.py", line 237, in build_model
    embedder = BertEmbedderModule(args)
  File "/srv/home/ericwallace/jiant/jiant/pytorch_transformers_interface/modules.py", line 275, in __init__
    args.input_module, cache_dir=self.cache_dir, output_hidden_states=True
  File "/home/ericwallace/miniconda3/envs/jiant/lib/python3.6/site-packages/pytorch_transformers/modeling_utils.py", line 528, in from_pretrained
    raise e
  File "/home/ericwallace/miniconda3/envs/jiant/lib/python3.6/site-packages/pytorch_transformers/modeling_utils.py", line 514, in from_pretrained
    resolved_archive_file = cached_path(archive_file, cache_dir=cache_dir, force_download=force_download, proxies=proxies)
  File "/home/ericwallace/miniconda3/envs/jiant/lib/python3.6/site-packages/pytorch_transformers/file_utils.py", line 118, in cached_path
    return get_from_cache(url_or_filename, cache_dir=cache_dir, force_download=force_download, proxies=proxies)
  File "/home/ericwallace/miniconda3/envs/jiant/lib/python3.6/site-packages/pytorch_transformers/file_utils.py", line 244, in get_from_cache
    http_get(url, temp_file, proxies=proxies)
  File "/home/ericwallace/miniconda3/envs/jiant/lib/python3.6/site-packages/pytorch_transformers/file_utils.py", line 184, in http_get
    for chunk in req.iter_content(chunk_size=1024):
  File "/home/ericwallace/miniconda3/envs/jiant/lib/python3.6/site-packages/requests/models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
